name = "RFRegistry"
uuid = "2c7d2912-e159-4f8c-8875-1959b6f4b3b8"
repo = "git@github.com:mastrof/RFRegistry.git"

[packages]
682643da-b995-4346-8c6a-9b654bba8793 = { name = "ParticleTracking", path = "P/ParticleTracking" }
72f87620-1546-45cd-8031-1f00e49166d6 = { name = "RingDetection", path = "R/RingDetection" }
